export const Events: Record<string, string> = {
	ROUTER_NAVIGATION: "routernav",
	TAG_MANAGER: "tag_manager",
	DATE_PICKER: "date_picker",
	GEOLOCATION: "geolocation",
	FOCUS_LAST_ENTRY: "focus_last_entry",
	OPEN_CAMERA: "open_camera",
	CLOSE_CAMERA: "close_camera",
	SET_AUDIO_RECORDING: "set_audio_recording",
	SET_VIDEO_RECORDING: "set_video_recording",
	SET_PHOTO: "set_photo",
	RELOAD_NOTES: "reload_notes",
	SET_INTENT: "set_intent",
	SCROLL_TO_LAST_ENTRY: "scroll_to_last_entry",
	SYNC_CHANGES_DETECTED: "sync_changes_detected",
	DEV_MODE_UNLOCKED: "dev_mode_unlocked",
	ADD_TRANSCRIPTION_TEXT: "add_transcription_text",
	SET_ENTRY_TRANSCRIPTION: "set_entry_transcription",
	SET_ENTRY_TRANSLATION: "set_entry_translation",
	NOTE_TAGS_UPDATED: "note_tags_updated",
	TAGS_UPDATED: "tags_updated",
}
